# Generated by Django 4.2 on 2024-01-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_employees_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='image',
        ),
    ]
