# Generated by Django 4.2 on 2024-01-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='image',
            field=models.ImageField(default=12, upload_to='Employee_images/'),
            preserve_default=False,
        ),
    ]
