# Generated by Django 4.2 on 2024-02-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_employees_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
