# Generated by Django 4.2 on 2024-02-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
