# Generated by Django 4.2 on 2024-02-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_task_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='statusi',
        ),
    ]
