# Generated by Django 4.2 on 2024-02-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_status_task_statusi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='statusi',
            new_name='status',
        ),
    ]
